### ISSUE TITLE
Action Items for Oct. 23:

### ISSUE THREAD

**Issue by ZacheryLaycock** [ZacheryLaycock/GALEX_MtWilson#4]
- [x] Jim: Send MySQL info/example
- [x] Zac: Login to MAST CasJobs 
- [x] Zac: run query for one star HD 3765

**Comment by ZacheryLaycock** [comment]
attn: @jradavenport

**Comment by jradavenport** [comment]
hm, i can't click my check box since i don't own the repository....

but can you check my box? email sent!

**Comment by ZacheryLaycock** [comment]
You got it!
Found the password after a little more brute forcing.

**Comment by ZacheryLaycock** [comment]
Working on setting up query. If you're still around feel free to stop by.

**Comment by jradavenport** [comment]
I vote this "Issue" gets closed.

Bravo, well done this quarter finding an interesting object!! The fun continues in 2018...

**Comment by ZacheryLaycock** [comment]
Cheers!
